version: "3"
services:
  app:
    container_name: notifications-api
    restart: always
    build:
      context: ./
      args:
        port: "3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules